export const CREATE_MULTISIG_TRANSACTION =
  "parcel/multisig/CREATE_MULTISIG_TRANSACTION";
export const CREATE_MULTISIG_TRANSACTION_SUCCESS =
  "parcel/multisig/CREATE_MULTISIG_TRANSACTION_SUCCESS";
export const CREATE_MULTISIG_TRANSACTION_ERROR =
  "parcel/multisig/CREATE_MULTISIG_TRANSACTION_ERROR";

export const GET_MULTISIG_TRANSACTIONS =
  "parcel/multisig/GET_MULTISIG_TRANSACTIONS";
export const GET_MULTISIG_TRANSACTIONS_SUCCESS =
  "parcel/multisig/GET_MULTISIG_TRANSACTIONS_SUCCESS";
export const GET_MULTISIG_TRANSACTIONS_ERROR =
  "parcel/multisig/GET_MULTISIG_TRANSACTIONS_ERROR";
