export const GET_SAFE_DETAILS = "parcel/safe/GET_SAFE_DETAILS";
export const GET_SAFE_DETAILS_SUCCESS = "parcel/safe/GET_SAFE_DETAILS_SUCCESS";
export const GET_SAFE_DETAILS_ERROR = "parcel/safe/GET_SAFE_DETAILS_ERROR";

export const CREATE_MULTISIG_TRANSACTION =
  "parcel/safe/CREATE_MULTISIG_TRANSACTION";
export const CREATE_MULTISIG_TRANSACTION_SUCCESS =
  "parcel/safe/CREATE_MULTISIG_TRANSACTION_SUCCESS";
export const CREATE_MULTISIG_TRANSACTION_ERROR =
  "parcel/safe/CREATE_MULTISIG_TRANSACTION_ERROR";

export const GET_MULTISIG_TRANSACTION = "parcel/safe/GET_MULTISIG_TRANSACTION";
export const GET_MULTISIG_TRANSACTION_SUCCESS =
  "parcel/safe/GET_MULTISIG_TRANSACTION_SUCCESS";
export const GET_MULTISIG_TRANSACTION_ERROR =
  "parcel/safe/GET_MULTISIG_TRANSACTION_ERROR";
